services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --bind-address=0.0.0.0
        networks:
            - laravel-network

    laravel:
        image: laravelphp/php-fpm
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-container
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel-network

    nginx:
        image: nginx:alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel
        networks:
            - laravel-network

volumes:
    mysql_data:

networks:
    laravel-network:
        driver: bridge
