services:
    laravel:
        image: laravelphp/php-fpm
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-container
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network

    nginx:
        image: nginx:alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel
        networks:
            - laravel-network

volumes:
    mysql_data:

networks:
    laravel-network:
        driver: bridge
