version: "3.8"

services:
    # Servicio de MySQL
    mysql:
        image: mysql:8.0-bookworm
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel-network

    # Servicio de Laravel
    laravel:
        image: laravelphp/php-fpm
        container_name: laravel-container
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - laravel-network

    # Servidor Nginx para Laravel
    nginx:
        image: nginx:alpine
        container_name: nginx-container
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network

volumes:
    mysql_data:

networks:
    laravel-network:
        driver: bridge
